### ISSUE TITLE
An error comes out when i use "annotate_video.py"

### ISSUE THREAD

**Issue by jiangkun1994** [Kelicious/faster_rcnn#1]
We are learning the network configuration about `faster-rcnn` currently, so i find out this great job you did. Right now, i have trained the data only from `PASCAL VOC2007` based on `resnet101` on Google Cloud Platform. After this, i got the result, but only on terminal and tmpout. So, i also want to give some images using `annotate_video.py` in order to plot the location box on these images from VOC2007, but i suffered from this error: 

> ValueError: operands could not be broadcast together with shapes (15390,) (30780,)

So, could you please help me out? Or could you please teach me how to plot the box to show the location of objects detected? I am quite new on deep learning. Thanks for your help and great work you did~

**Comment by Kelicious** [comment]
Hi jiangkun1994, what line of code was being executed when you got that error? Without more details, I would guess there's something wrong with the image dimensions.

**Comment by jiangkun1994** [comment]
Thanks for you replying! The code being executed is in `faster_rcnn/util.py`, it is line 129 in this file, which is: 

> coords[:,0] += tx * coords[:,2]

maybe i do this annotation in a wrong way, i am a bit confused about this part.

**Comment by jiangkun1994** [comment]
I am using command line: 

> python faster_rcnn/annotate_video.py models/rpn_model_r101_fullreg_step3_voc2007_train.h5 models/detector_model_r101_fullreg_step4_voc2007_train.h5 test_images/ --out_dir ./images_out

In `test_images` directory, i put some images from VOC2007 in it, since i want to plot the bounding box to these images.

**Comment by jiangkun1994** [comment]
The details are as following: 

> /home/jiangkunhaha/anaconda3/envs/faster_rcnn/lib/python3.5/site-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
processing test/000078.jpg
Traceback (most recent call last):
  File "faster_rcnn/annotate_video.py", line 82, in <module>
    resize_max=resize_max)
  File "faster_rcnn/annotate_video.py", line 22, in annotate_images
    annotated_frame = get_annotated_frame(training_manager, detector, frame, img, resize_min, resize_max)
  File "faster_rcnn/annotate_video.py", line 30, in get_annotated_frame
    resize_ratio=resized_ratios[0], det_threshold=0.0)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/voc_dets.py", line 22, in get_dets
    conv_out, rois = training_manager.get_det_inputs(image)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/custom_decorators.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/det_util.py", line 145, in get_det_inputs
    roi_coords, roi_probs, conv_out = self._rois_from_image(image)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/custom_decorators.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/det_util.py", line 52, in _rois_from_image
    roi_coords = self._get_rois(regr_out, self.anchor_dims)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/custom_decorators.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/det_util.py", line 60, in _get_rois
    return _get_rois(regr_out, anchor_dims, self.stride)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/custom_decorators.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/det_util.py", line 376, in _get_rois
    rois = transform_np_inplace(anchor_coords, reg_targets / BBREG_MULTIPLIERS)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/custom_decorators.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/home/jiangkunhaha/faster_rcnn/faster_rcnn/util.py", line 129, in transform_np_inplace
    coords[:,0] += tx * coords[:,2]
ValueError: operands could not be broadcast together with shapes (15390,) (30780,)

**Comment by Kelicious** [comment]
Since 30780 is 2x 15390, I think either the image size is wrong or you used a different number of anchor scales between training and testing. I only used annotate_video for KITTI so I didn't add a flag to change the number of anchor scales for VOC data. Try replacing the anchor scales in shared_constants.py with DEFAULT_ANCHOR_SCALES = np.array([128, 256, 512])

**Comment by jiangkun1994** [comment]
Thank you so much ! I replaced the anchor scales and it works!! Thx!
